# NOTE: update this with your service name
service: serverless-faucet

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  stage: dev
  bundle:
    linting: false             # Enables linting as a part of the build process
    caching: false
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux --target=12.10.0 sharp

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  verify-captcha:
    handler: authorizer.verifyCaptcha
  captcha:
    handler: handler.captcha
    events:
      - http:
          path: captcha/{columns}/{rows}
          method: get
  faucet:
    handler: handler.fundAccount
    events:
      - http:
          path: faucet/{network}/{address}
          method: get
          cors: true
          authorizer: verify-captcha